LAB_DESCRIPTION="This network will be used to demonstrate the effectiveness of known attack chains against an insecure network."
LAB_VERSION=2026
LAB_AUTHOR="Aeden Hastie"
LAB_EMAIL=Aeden.Hastie@student.uts.edu.au

#internet dmz it_lan ot_dmz ot_lan

#attacker edge-fw dc01 fileserver admin-ws jumpbox plc-unitronics-sim plc-rockwell-sim plc-siemens-sim (o) plc-schneider-sim (o) hmi-scada

#internet
attacker[0]=internet
edge_fw[0]=internet

#dmz
edge_fw[1]=dmz
ot_fw[0]=dmz

#it_lan
edge_fw[2]=it_lan
dc01[0]=it_lan
admin[0]=it_lan
fileserver[0]=it_lan

#ot_dmz
ot_fw[1]=ot_dmz
jumpbox[0]=ot_dmz

#ot_lan
ot_fw[2]=ot_lan
unitronics[0]=ot_lan
rockwell[0]=ot_lan
siemens[0]=ot_lan
schneider[0]=ot_lan
opconsole[0]=ot_lan